### ISSUE TITLE
🚧Convert action to dotnet

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionValidator#17]
### I have done the items below . . .

- [X] I have created a title but left the 🚧 emoji behind.

### Description

Convert this GitHub action from typescript/javascript style to C# style project.  To help speed things up, rename this project by prefixing the end with OLD.  Then create a new project using the new [DotNetGitHubActionTemplate](https://github.com/KinsonDigital/DotNetGitHubActionTemplate) template repo.

Then use the old code base as a guide to help rebuild this new action.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Action converted
- [ ] Unit tests created
- [ ] All unit tests pass
- [ ] Do not carry over any nuget functionality.  This has all been moved to new github actions.
  - This functionality will simply be removed.  
- [ ] For validating version, use the glob syntax concept for matching
  - Refer to the [BranchValidator](https://github.com/KinsonDigital/BranchValidator) project burrow code and see how this is done

### ToDo Items

- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked  to the project milestone

**Comment by CalvinWilkinson** [comment]
Put on hold.

Need to research if github actions can be built with deno.  If so, then this issue can be deleted.
