### ISSUE TITLE
🚧Update actions/core package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionValidator#49]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the **_actions/core_** package to the latest version.

This update is required due to changes that GitHub has made to how action outputs are dealt with.  This is a security update.

Click [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) for more information.

**Package to update:**
```diff
 "dependencies": {
-    "@actions/core": "^1.4.0",
+    "@actions/core": "^1.10.0",
    "@actions/github": "^5.0.0",
    "@vercel/ncc": "^0.28.6",
    "axios": "^0.21.1",
    "node": "^16.5.0",
    "reflect-metadata": "^0.1.13",
    "tsyringe": "^4.6.0"
  },
```

### Acceptance Criteria

- [ ] _**actions/core**_ package updated to latest version.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
